[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwasm = "0.5.0"
types = { path= "../types"}
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["HtmlInputElement"] }
yew = { version = "0.21.0", features = ["csr"] }
