[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwasm = "0.5.0"
types = { path= "../types"}
wasm-bindgen-futures = "0.4.42"
yew = { version = "0.21.0", features = ["csr"] }
